version: '3.8'
services:
  db:
    build: .
    volumes:
      - db_storage:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "6543:5432"
    restart: always

  app:
    depends_on:
      - db
    entrypoint: 'nodemon --watch src/ src/index.js'
    environment:
      PATH: '$PATH:/app/node_modules/.bin/'
    image: node:16.9-alpine
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./node_modules:/app/node_modules:cached
      - ./src:/app/src:cached
    working_dir: /app

volumes:
  db_storage:
