version: '3.8'
services:
  db:
    build: .
    volumes:
      - db_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "6543:5432"

volumes:
  db_storage:
